---
# main job for GitLab Pages is called pages 
# run on a push on master branch only
pages:
  stage: deploy
  tags:
    - ci.inria.fr
    - small
  image: docker:stable
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

# add another job to test every push to every branch except the master branch
test:
  stage: test
  script:
    - bundle exec jekyll build -d test
  artifacts:
    paths:
      - test
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'

# requiring the environment of Ruby 2.7.x
image: ruby:3.1.2

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

# cache dependencies to 'vendor/' dir for speeding up builds
cache:
  paths:
    - vendor/

# avoid duplicating the same scripts in every job below
before_script:
  - ruby -v # Print out ruby version for debugging
# - gem install bundler
#  - bundle config set --local path 'vendor'
#  - bundle update

