# Site settings

title: "Florent Jacquemard"
theme: jekyll-theme-minimal
logo: /assets/img/logo.png
email: florent.jacquemard@inria.fr
description: > # this means to ignore newlines until "baseurl:"
    Florent Jacquemard Homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jacquema.gitlabpages.inria.fr" # the base hostname & protocol for your site
show_downloads: true
google_analytics:

twitter_username: jekyllrb
github_username:  florento
gitlab_username:  jacquema
