
resume_contact_telephone:       "+33 1 80 49 43 23‬"

resume_contact_address:         "2 rue Simone Iff 75589 Paris Cedex 12 France"

resume_header_contact_info:     "Centre de Recherche Inria de Paris. 2 rue Simone Iff 75589 Paris Cedex 12 • +33 6 50 08 84 53 • first.lastname@inria.fr"